# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# We generate the client here for the build
RUN npx prisma@6 generate
RUN npm run build

# Stage 2: Run
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV production

# --- THE FIX: Install Prisma CLI globally so entrypoint can use it ---
RUN npm install -g prisma@6.19

# Add required libs
RUN apk add --no-cache openssl

# Copy necessary files
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
# Important: Ensure the schema is copied so Prisma knows what to push
COPY --from=builder /app/prisma ./prisma
COPY ./app/entrypoint.sh ./

# Ensure entrypoint is executable
RUN chmod +x entrypoint.sh

EXPOSE 3000
ENTRYPOINT ["./entrypoint.sh"]